### ISSUE TITLE
Teleporting on Interaction Cancel

### ISSUE THREAD

**Issue by celedev97** [Spooni-Development/spooni_interactions#1]
If you interact with a chair that's on a train, then the train moves, when you cancel the interaction you will teleport back to where you were when you started the interaction, miles away.

When an interaction starts instead of saving the player ped coords it would be better to save the offset between the interaction coords and the player ped coords, so when the animation is cancelled you could set the player ped position to the position of the object shifted by the offset.

**Comment by TimGehring** [comment]
Hey, thanks for your report! I made a few changes today, can you check if the problem still exists. :D
